create extension if not exists "postgis" schema "extensions";
create extension if not exists "pgcrypto" schema "extensions";

create type "public"."mediaType" as enum (
    'StillImage',
    'MovingImage',
    'Text',
    'Sound',
    'InteractiveResource',
    'Image'
);

comment on type "public"."mediaType" is 'Types of media assets stored in object storage';

create table "public"."collections" (
    "id" bigint generated by default as identity primary key,
    "title" text not null,
    "institution" text not null,
    "city" text not null,
    "country" text not null,
    "created_at" timestamp with time zone not null default now()
);

create table "public"."items" (
    "id" bigint generated by default as identity,
    "title" text not null,
    "description" text,
    "date" text,
    "created_at" timestamp with time zone not null default now(),
    "collection" bigint references "public"."collections"("id") on update cascade on delete set null,
    "external_id" uuid not null default gen_random_uuid() unique,
    "location" extensions.geography,
    "latitude" double precision generated always as (extensions.st_y(("location")::extensions.geometry)) stored,
    "longitude" double precision generated always as (extensions.st_x(("location")::extensions.geometry)) stored,
    constraint "objects_pkey" primary key ("id")
);

create index "items_geo_index" on "public"."items" using gist ("location");

create table "public"."media" (
    "id" bigint generated by default as identity primary key,
    "title" text not null,
    "description" text,
    "date" date,
    "storage_key" text not null,
    "created_at" timestamp with time zone not null default now(),
    "media_type" "public"."mediaType" not null default 'StillImage'
);

comment on column "public"."media"."media_type" is 'Type of stored media';

create table "public"."assets" (
    "id" bigint generated by default as identity primary key,
    "item" bigint not null references "public"."items"("id") on update cascade on delete cascade,
    "media" bigint not null references "public"."media"("id") on update cascade on delete cascade,
    "created_at" timestamp with time zone not null default now()
);

create table "public"."archivematica_transfers" (
    "id" uuid not null default gen_random_uuid() primary key,
    "item_id" bigint not null references "public"."items"("id") on update cascade on delete cascade,
    "status" text not null default 'queued',
    "transfer_name" text not null,
    "am_transfer_uuid" text,
    "am_sip_uuid" text,
    "current_microservice" text,
    "package_s3_key" text,
    "error_message" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

create table "public"."archivematica_transfer_events" (
    "id" uuid not null default gen_random_uuid() primary key,
    "transfer_id" uuid not null references "public"."archivematica_transfers"("id") on update cascade on delete cascade,
    "event_type" text not null,
    "microservice" text,
    "message" text,
    "raw" jsonb,
    "created_at" timestamp with time zone not null default now()
);

create or replace function "public"."items_in_view"(
    "min_lat" double precision,
    "min_long" double precision,
    "max_lat" double precision,
    "max_long" double precision
) returns table("id" bigint, "name" text, "lat" double precision, "long" double precision)
    language sql
    set search_path to ''
    as $$
    select id, title, extensions.st_y(location::extensions.geometry) as lat, extensions.st_x(location::extensions.geometry) as long
    from public.items
    where location operator(extensions.&&) extensions.ST_SetSRID(extensions.ST_MakeBox2D(extensions.ST_Point(min_long, min_lat), extensions.ST_Point(max_long, max_lat)), 4326)
$$;

grant all on function "public"."items_in_view"(double precision, double precision, double precision, double precision) to anon, authenticated, service_role;

alter table "public"."collections" enable row level security;
alter table "public"."items" enable row level security;
alter table "public"."media" enable row level security;
alter table "public"."assets" enable row level security;
alter table "public"."archivematica_transfers" enable row level security;
alter table "public"."archivematica_transfer_events" enable row level security;

create policy "read access" on "public"."collections" for select using (true);
create policy "Enable insert for authenticated users only" on "public"."collections" for insert to authenticated with check (true);

create policy "public access" on "public"."items" for select using (true);
create policy "Enable insert for authenticated users only" on "public"."items" for insert to authenticated with check (true);

create policy "read access" on "public"."media" for select using (true);
create policy "Enable insert for authenticated users only" on "public"."media" for insert to authenticated with check (true);

create policy "read access" on "public"."assets" for select using (true);
create policy "Enable insert for authenticated users only" on "public"."assets" for insert to authenticated with check (true);

grant all on table "public"."collections" to anon, authenticated, service_role;
grant all on table "public"."items" to anon, authenticated, service_role;
grant all on table "public"."media" to anon, authenticated, service_role;
grant all on table "public"."assets" to anon, authenticated, service_role;
grant all on table "public"."archivematica_transfers" to anon, authenticated, service_role;
grant all on table "public"."archivematica_transfer_events" to anon, authenticated, service_role;
